// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhAfXDUmjBkQc7-89q55HQC6_JsZ9bWIU',
    appId: '1:338367323034:web:68938447c4f866f99e3823',
    messagingSenderId: '338367323034',
    projectId: 'to-do-app--flutter',
    authDomain: 'to-do-app--flutter.firebaseapp.com',
    storageBucket: 'to-do-app--flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBISfaKRkVjSjRDWmfwZsowAgaycSjBR6E',
    appId: '1:338367323034:android:defb2ca507206dff9e3823',
    messagingSenderId: '338367323034',
    projectId: 'to-do-app--flutter',
    storageBucket: 'to-do-app--flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ1X4K2dKlSuFG1xyWSL081jUMRx7eftQ',
    appId: '1:338367323034:ios:b68fac461828798c9e3823',
    messagingSenderId: '338367323034',
    projectId: 'to-do-app--flutter',
    storageBucket: 'to-do-app--flutter.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ1X4K2dKlSuFG1xyWSL081jUMRx7eftQ',
    appId: '1:338367323034:ios:6062d5ed3aa976579e3823',
    messagingSenderId: '338367323034',
    projectId: 'to-do-app--flutter',
    storageBucket: 'to-do-app--flutter.appspot.com',
    iosBundleId: 'com.example.toDo.RunnerTests',
  );
}
